language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew shadowJar"
deploy:
- provider: script
  overwrite: true
  script: "./gradlew bintrayUpload --info"
  skip_cleanup: true
  on:
    repo: hmcts/idam-forgerock-notify-client
    tags: true
env:
  global:
  - secure: e9tzuHhE373J7FKEN9C64sbZ09Go21a7FYWIHvTNfBSmKaJcrc81oWyYGsqLrumGsFFw62134b/MuyCZiWgbgEgKBGgXKqUW7WdkCN+waAd3YpYrzbkYK8EQaQyIlTEOAQCpc5L0sSDGpzGxSTZg6n3Fgh4U1wzL7JSrZ6a5fHvt8FYw5z9wAExIcndq0rtsNoe58XvHaC+f9JTBMrRbjF63cSPrLYzyh5zZ6EekGy3iXLgFdpTBC39Wd4mAsKqj5zJyhGBtCaLJQYxhsg+7KJ+ffxNBttdCe2DXwBwA7zcfPGGDEFzMTSDFfreg2O75bjJ9SWWfQWmYlSPVBI4lX/BUxAnpiluLj8XlxX9DyHhAT45hXB1ELwXGSpMg07O7scVcK1A4DiU91O/GzhKgKRhtAwFihNEFg/7rhvMnO4CGPR5Sckz9tPX4AFMdtqZF0vARh3vpPGuYF/gfNX8HpGx7pxj0ejZUNLmclYv6HxXB/J3fBMe9jPK1E1DZ7vSaVBJAJBoohbG1SPiIqRHQzvbcaq/hlTT/s3tqk2ejZxakJacVSs8cSCYZmM2YgWqyfVRGtkrklUkH4/Yo+6rrFKnXazYeq75MJV7Lobl+m+fdben2w7O2/eHHgVwgCmmUg18+ozgm7/dyPJ0vPdYzhtpjIJtRopw4Ir37Q+85oMc=
  - secure: ifsrd3yAZshfY1/jWg+/QQ4l4jl9b1OF0B7nxVzprOgJejNQopIgHUV4dwRbrP+GLFjIxFhOqK71YDRBq8eVRvHbo2HKSog6YNII4+V7pYQThrBeblp7z7dr2ijTV2f5XqfhnkcrzhnMWbs03Bu4TGYUh6iaK/OWt79tm51Mh09GZT9oyGwcF/6A4FqTMlyazdCrBbmeEh1IoPqCA6MAjDWH5tIaGQ3ukawgCpxmK3SJv0D0xianp82Uj3+t7T045JiwquMrNSC85zanWzTWl7yZlVjWKQI3lV/0pDawhSRhZiVfw/QPa+XgfMx+R8uM2kvNIr8VCjOrZ4qFi0onTIU1hg3uaic2OjTCqHRuyDD0dBGkpPOtaP6ohpdPadXxSJjO+KSSOP3TavvJ+v9+7JkGRQmBEfy+FaaQjgVp6RhMJijd1MEvuGKNvhkuk94b3+Y9176T/Dr6oZCTNqmoR2+j0B2vHbdFOHqlwS2Y2uB5hF8gw5tJwJsHTKgNJJ4uLg5KkISRGFvApUJWfsX4FFMoSe5cbHMF+wO1JG6GFVYUZD/p6JbrWpANud/Cgn4WCYw89/+RInIPwT+JY+nH5N3AgHl1dpI5iRQfN5pwGTwkkSyTeBLmuk5ZDNwHpVcEb5PXI6hdN/HRP+fznovI3m62AY8AhFpBy5GSM01gWwg=
